### ISSUE TITLE
BUG-Case sensitivity with mail adresses

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#231] opened 2020-06-20 18:01 UTC
e-mail addresses should not be case-sensitive when sending and receiving

**Comment by drjakob** [comment] 2020-06-20 18:08
Till will deoploy this

**Comment by tillprochaska** [comment] 2020-06-21 13:37
Duplicate of #224

**Comment by drjakob** [comment] 2020-10-28 19:14
Please fix again

**Comment by drjakob** [comment] 2020-10-28 19:16
Mustermann@hotmail.com, MUSTERmann@hotmail.com and mustermann@hotmail.com should all be treated as mustermann@hotmail.com

**Comment by FrauCsu** [comment] 2020-10-28 21:03
Yes, very URGENT. Who resolves it, @tillprochaska @mattwr18 @roschaefer @phoeinx ?

**Comment by tillprochaska** [comment] 2020-10-29 09:52
I’m pretty sure the issue you reported isn’t related to case-sensitive/insensitive addresses as contributors aren’t receiving *our* emails. Case-insensitive addresses are only important when we receive new emails, as we need to match the senders email address to the addresses in our database.

I’ll keep this open though until I’ve had a closer look at the problems. I guess it’s related to general deliverability/spam issues.

**Comment by phoeinx** [comment] 2020-10-29 13:27
Short question - what is the exact issue Till is referring to with "contributors aren't receiving our emails" - as in not at all? Couldn't find a bug report / issue for that (at least none that is open) and no mention in Slack, where have I forgotten to look / overlooked ?

**Comment by tillprochaska** [comment] 2020-10-29 14:39
@phoeinx @mattwr18 I added you to our feedback channel in Slack. In this case, Isa posted there to let us know about this issue.

**Closed** 2020-10-29 22:58 UTC
Labels: bug
