### ISSUE TITLE
BUG reply to an image on threema

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1531] opened 2022-11-18 08:40 UTC
I replied to an image sent out to Threema. Quoted is nit the image but the ID.
<img width="743" alt="Bildschirm­foto 2022-11-18 um 09 38 38" src="https://user-images.githubusercontent.com/11591426/202658667-f94ac9d2-64e5-456c-9ce8-1a89811551bc.png">

**Comment by mattwr18** [comment] 2022-11-20 10:51
Closing this as we discussed in [Slack](https://tactilenews.slack.com/archives/C03JJLC9HU1/p1668760747660079) and this is not a bug. It's a feature that we have not implemented and already have an issue for. [Tracking issue: Allow to quote message in reply from newsroom #1478](https://github.com/tactilenews/100eyes/issues/1478)

**Closed by mattwr18** 2022-11-20 10:51 UTC
