### ISSUE TITLE
BUG Image Counter

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#951] opened 2021-06-28 06:44 UTC
(Threema?) Images are not counted correctly
<img width="1097" alt="Bildschirmfoto 2021-06-28 um 08 43 00" src="https://user-images.githubusercontent.com/11591426/123592081-0ff70500-d7ed-11eb-9399-b29c5119938d.png">

**Comment by tillprochaska** [comment] 2021-06-28 07:23
Duplicate of #813

**Closed by tillprochaska** 2021-06-28 07:24 UTC
Labels: bug
