### ISSUE TITLE
Change of link on oboarding site - top right

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#859] opened 2021-05-07 09:07 UTC
Currently the onboarding page shows a link on the top right corner "Eine Dialogrecherche von tactile.news". This needs to be customized for each client so it's a link to their newsroom, not ours.

**Comment by tillprochaska** [comment] 2021-05-07 10:03
This is a duplicate of #842

**Closed by tillprochaska** 2021-05-07 10:03 UTC
Labels: urgent
